version: '3'
services:
  elasticsearch-node1:
    image: elasticsearch:7.12.0
    container_name: elasticsearch-node1
    environment:
      - node.name=node-1
      - discovery.seed_hosts=elasticsearch-node2
      - cluster.initial_master_nodes=node-1,node-2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - esnet

  elasticsearch-node2:
    image: elasticsearch:7.12.0
    container_name: elasticsearch-node2
    environment:
      - node.name=node-2
      - discovery.seed_hosts=elasticsearch-node1
      - cluster.initial_master_nodes=node-1,node-2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9201:9200"
    networks:
      - esnet

  kibana:
    image: kibana:7.12.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet

networks:
  esnet:
    name: elastic
    external: true
